#include "custom_keycodes.h"
#include "process_combo.h"
#include "layers.h"

enum combo_events { ARTSEY_H, ARTSEY_Q, ARTSEY_U, ARTSEY_C, ARTSEY_K, ARTSEY_B, ARTSEY_W, ARTSEY_N, ARTSEY_F, ARTSEY_X, ARTSEY_J, ARTSEY_M, ARTSEY_P, ARTSEY_V, ARTSEY_L, ARTSEY_Z, ARTSEY_D, ARTSEY_G, ARTSEY_SPACE, ARTSEY_SPACE_2, ARTSEY_BACKSPACE, ARTSEY_BACKSPACE_2, ARTSEY_DEL, ARTSEY_DEL_2, ARTSEY_ENTER, ARTSEY_ENTER_2, ARTSEY_ESCAPE, ARTSEY_ESCAPE_2, ARTSEY_QUOTE, ARTSEY_BANG, ARTSEY_QUEST, ARTSEY_PERIOD, ARTSEY_COMMA, ARTSEY_SLASH, ARTSEY_TAB, ARTSEY_OS_SHIFT, ARTSEY_CTRL, ARTSEY_CTRL_2, ARTSEY_CTRL_3, ARTSEY_GUI, ARTSEY_GUI_2, ARTSEY_GUI_3, ARTSEY_ALT, ARTSEY_ALT_2, ARTSEY_ALT_3, ARTSEY_SHIFT, ARTSEY_SHIFT2, ARSEY_PANIC, ARSEY_PANIC_2, ARSEY_PANIC_3, ARTSEY_NAV, ARTSEY_MAIN1, ARTSEY_MOU, ARTSEY_MAIN2, ARTSEY_7, ARTSEY_8, ARTSEY_9, ARTSEY_0, COMBO_LENGTH };
uint16_t               COMBO_LEN            = COMBO_LENGTH;
const uint16_t PROGMEM artsey_h[]           = {BASE_2_4, BASE_2_2, COMBO_END};
const uint16_t PROGMEM artsey_q[]           = {BASE_1_4, BASE_1_2, BASE_1_1, COMBO_END};
const uint16_t PROGMEM artsey_u[]           = {BASE_2_3, BASE_2_2, COMBO_END};
const uint16_t PROGMEM artsey_c[]           = {BASE_2_4, BASE_2_3, COMBO_END};
const uint16_t PROGMEM artsey_k[]           = {BASE_2_3, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_b[]           = {BASE_2_4, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_w[]           = {BASE_1_4, BASE_1_1, COMBO_END};
const uint16_t PROGMEM artsey_n[]           = {BASE_2_2, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_f[]           = {BASE_1_4, BASE_1_3, COMBO_END};
const uint16_t PROGMEM artsey_x[]           = {BASE_1_3, BASE_1_2, BASE_1_1, COMBO_END};
const uint16_t PROGMEM artsey_j[]           = {BASE_1_2, BASE_1_1, COMBO_END};
const uint16_t PROGMEM artsey_m[]           = {BASE_2_3, BASE_2_2, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_p[]           = {BASE_2_4, BASE_2_2, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_v[]           = {BASE_1_3, BASE_1_1, COMBO_END};
const uint16_t PROGMEM artsey_l[]           = {BASE_2_4, BASE_2_3, BASE_2_2, COMBO_END};
const uint16_t PROGMEM artsey_z[]           = {BASE_1_4, BASE_1_3, BASE_1_2, BASE_1_1, COMBO_END};
const uint16_t PROGMEM artsey_d[]           = {BASE_1_4, BASE_1_3, BASE_1_2, COMBO_END};
const uint16_t PROGMEM artsey_g[]           = {BASE_1_3, BASE_1_2, COMBO_END};
const uint16_t PROGMEM artsey_space[]       = {BASE_2_4, BASE_2_3, BASE_2_2, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_space_2[]     = {NAV_2_4, NAV_2_3, NAV_2_2, NAV_2_1, COMBO_END};
const uint16_t PROGMEM artsey_backspace[]   = {BASE_2_4, BASE_1_3, COMBO_END};
const uint16_t PROGMEM artsey_backspace_2[] = {NAV_2_4, NAV_1_3, COMBO_END};
const uint16_t PROGMEM artsey_del[]         = {BASE_1_3, BASE_2_2, COMBO_END};
const uint16_t PROGMEM artsey_del_2[]       = {NAV_1_3, NAV_2_2, COMBO_END};
const uint16_t PROGMEM artsey_enter[]       = {BASE_1_4, BASE_2_4, COMBO_END};
const uint16_t PROGMEM artsey_enter_2[]     = {NAV_1_4, NAV_2_4, COMBO_END};
const uint16_t PROGMEM artsey_escape[]      = {BASE_1_4, BASE_1_3, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_escape_2[]    = {NAV_1_4, NAV_1_3, NAV_2_1, COMBO_END};
const uint16_t PROGMEM artsey_quote[]       = {BASE_1_3, BASE_2_3, COMBO_END};
const uint16_t PROGMEM artsey_bang[]        = {BASE_1_2, BASE_2_2, COMBO_END};
const uint16_t PROGMEM artsey_quest[]       = {BASE_1_1, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_period[]      = {BASE_1_4, BASE_2_2, COMBO_END};
const uint16_t PROGMEM artsey_comma[]       = {BASE_1_4, BASE_2_3, COMBO_END};
const uint16_t PROGMEM artsey_slash[]       = {BASE_1_4, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_tab[]         = {BASE_1_4, BASE_1_3, BASE_1_2, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_os_shift[]    = {BASE_2_4, BASE_1_3, BASE_1_2, BASE_1_1, COMBO_END};
const uint16_t PROGMEM artsey_ctrl[]        = {BASE_1_1, BASE_2_4, COMBO_END};
const uint16_t PROGMEM artsey_ctrl_2[]      = {NAV_1_1, NAV_2_4, COMBO_END};
const uint16_t PROGMEM artsey_ctrl_3[]      = {MOU_1_1, MOU_2_4, COMBO_END};
const uint16_t PROGMEM artsey_gui[]         = {BASE_1_1, BASE_2_3, COMBO_END};
const uint16_t PROGMEM artsey_gui_2[]       = {NAV_1_1, NAV_2_3, COMBO_END};
const uint16_t PROGMEM artsey_gui_3[]       = {MOU_1_1, MOU_2_3, COMBO_END};
const uint16_t PROGMEM artsey_alt[]         = {BASE_1_1, BASE_2_2, COMBO_END};
const uint16_t PROGMEM artsey_alt_2[]       = {NAV_1_1, NAV_2_2, COMBO_END};
const uint16_t PROGMEM artsey_alt_3[]       = {MOU_1_1, MOU_2_2, COMBO_END};
const uint16_t PROGMEM artsey_shift[]       = {BASE_1_4, BASE_2_3, BASE_2_2, BASE_2_1, COMBO_END};
const uint16_t PROGMEM artsey_shift2[]      = {NAV_1_4, NAV_2_3, NAV_2_2, NAV_2_1, COMBO_END};
const uint16_t PROGMEM arsey_panic[]        = {BASE_1_4, BASE_1_3, BASE_1_2, BASE_1_1, BASE_2_4, BASE_2_3, BASE_2_2, BASE_2_1, COMBO_END};
const uint16_t PROGMEM arsey_panic_2[]      = {NAV_1_4, NAV_1_3, NAV_1_2, NAV_1_1, NAV_2_4, NAV_2_3, NAV_2_2, NAV_2_1, COMBO_END};
const uint16_t PROGMEM arsey_panic_3[]      = {MOU_1_4, MOU_1_3, MOU_1_2, MOU_1_1, MOU_2_4, MOU_2_3, MOU_2_2, MOU_2_1, COMBO_END};
const uint16_t PROGMEM artsey_nav[]         = {BASE_1_3, BASE_2_4, BASE_2_2, COMBO_END};
const uint16_t PROGMEM artsey_main1[]       = {NAV_1_3, NAV_2_4, NAV_2_2, COMBO_END};
const uint16_t PROGMEM artsey_mou[]         = {BASE_1_4, BASE_1_2, BASE_2_3, COMBO_END};
const uint16_t PROGMEM artsey_main2[]       = {MOU_1_4, MOU_1_2, MOU_2_3, COMBO_END};
const uint16_t PROGMEM artsey_7[]           = {NUM_1_3, NUM_1_4, COMBO_END};
const uint16_t PROGMEM artsey_8[]           = {NUM_1_2, NUM_1_3, COMBO_END};
const uint16_t PROGMEM artsey_9[]           = {NUM_2_3, NUM_2_4, COMBO_END};
const uint16_t PROGMEM artsey_0[]           = {NUM_2_2, NUM_2_3, COMBO_END};
combo_t                key_combos[]         = {
    [ARTSEY_H]           = COMBO(artsey_h, KC_H),
    [ARTSEY_Q]           = COMBO(artsey_q, KC_Q),
    [ARTSEY_U]           = COMBO(artsey_u, KC_U),
    [ARTSEY_C]           = COMBO(artsey_c, KC_C),
    [ARTSEY_K]           = COMBO(artsey_k, KC_K),
    [ARTSEY_B]           = COMBO(artsey_b, KC_B),
    [ARTSEY_W]           = COMBO(artsey_w, KC_W),
    [ARTSEY_N]           = COMBO(artsey_n, KC_N),
    [ARTSEY_F]           = COMBO(artsey_f, KC_F),
    [ARTSEY_X]           = COMBO(artsey_x, KC_X),
    [ARTSEY_J]           = COMBO(artsey_j, KC_J),
    [ARTSEY_M]           = COMBO(artsey_m, KC_M),
    [ARTSEY_P]           = COMBO(artsey_p, KC_P),
    [ARTSEY_V]           = COMBO(artsey_v, KC_V),
    [ARTSEY_L]           = COMBO(artsey_l, KC_L),
    [ARTSEY_Z]           = COMBO(artsey_z, KC_Z),
    [ARTSEY_D]           = COMBO(artsey_d, KC_D),
    [ARTSEY_G]           = COMBO(artsey_g, KC_G),
    [ARTSEY_SPACE]       = COMBO(artsey_space, KC_SPACE),
    [ARTSEY_SPACE_2]     = COMBO(artsey_space_2, KC_SPACE),
    [ARTSEY_BACKSPACE]   = COMBO(artsey_backspace, KC_BACKSPACE),
    [ARTSEY_BACKSPACE_2] = COMBO(artsey_backspace_2, KC_BACKSPACE),
    [ARTSEY_DEL]         = COMBO(artsey_del, KC_DELETE),
    [ARTSEY_DEL_2]       = COMBO(artsey_del_2, KC_DELETE),
    [ARTSEY_ENTER]       = COMBO(artsey_enter, KC_ENTER),
    [ARTSEY_ENTER_2]     = COMBO(artsey_enter_2, KC_ENTER),
    [ARTSEY_ESCAPE]      = COMBO(artsey_escape, KC_ESCAPE),
    [ARTSEY_ESCAPE_2]    = COMBO(artsey_escape_2, KC_ESCAPE),
    [ARTSEY_QUOTE]       = COMBO(artsey_quote, KC_QUOTE),
    [ARTSEY_BANG]        = COMBO(artsey_bang, KC_HASH),
    [ARTSEY_QUEST]       = COMBO(artsey_quest, KC_QUESTION),
    [ARTSEY_PERIOD]      = COMBO(artsey_period, KC_DOT),
    [ARTSEY_COMMA]       = COMBO(artsey_comma, KC_COMMA),
    [ARTSEY_SLASH]       = COMBO(artsey_slash, KC_SLASH),
    [ARTSEY_TAB]         = COMBO(artsey_tab, KC_TAB),
    [ARTSEY_OS_SHIFT]    = COMBO(artsey_os_shift, OS_LSFT),
    [ARTSEY_CTRL]        = COMBO(artsey_ctrl, TOGGLE_CONTROL),
    [ARTSEY_CTRL_2]      = COMBO(artsey_ctrl_2, TOGGLE_CONTROL),
    [ARTSEY_CTRL_3]      = COMBO(artsey_ctrl_3, TOGGLE_CONTROL),
    [ARTSEY_GUI]         = COMBO(artsey_gui, TOGGLE_GUI),
    [ARTSEY_GUI_2]       = COMBO(artsey_gui_2, TOGGLE_GUI),
    [ARTSEY_GUI_3]       = COMBO(artsey_gui_3, TOGGLE_GUI),
    [ARTSEY_ALT]         = COMBO(artsey_alt, TOGGLE_ALT),
    [ARTSEY_ALT_2]       = COMBO(artsey_alt_2, TOGGLE_ALT),
    [ARTSEY_ALT_3]       = COMBO(artsey_alt_3, TOGGLE_ALT),
    [ARTSEY_SHIFT]       = COMBO(artsey_shift, TOGGLE_SHIFT),
    [ARTSEY_SHIFT2]      = COMBO(artsey_shift2, TOGGLE_SHIFT),
    [ARSEY_PANIC]        = COMBO(arsey_panic, PANIC),
    [ARSEY_PANIC_2]      = COMBO(arsey_panic_2, PANIC),
    [ARSEY_PANIC_3]      = COMBO(arsey_panic_3, PANIC),
    [ARTSEY_NAV]         = COMBO(artsey_nav, TO(_ART_NAV)),
    [ARTSEY_MAIN1]       = COMBO(artsey_main1, TO(_ART_BASE)),
    [ARTSEY_MOU]         = COMBO(artsey_mou, TO(_ART_MOU)),
    [ARTSEY_MAIN2]       = COMBO(artsey_main2, TO(_ART_BASE)),
    [ARTSEY_7]           = COMBO(artsey_7, KC_7),
    [ARTSEY_8]           = COMBO(artsey_8, KC_8),
    [ARTSEY_9]           = COMBO(artsey_9, KC_9),
    [ARTSEY_0]           = COMBO(artsey_0, KC_0),
};
